###############################################################################
#                        EssentialsCore Configuration                         #
###############################################################################
# Version 1.0.12

#---------------------------------
# Core Settings
#---------------------------------
core:
  # Debug mode enables detailed logs
  debug: false
  # Plugin message prefix
  prefix: "&8[&b&lApiCore&8] &7"
  # Automatically extract module resources
  extract-resources: true

#---------------------------------
# Module System
#---------------------------------
modules:
  # Automatically load modules on startup
  auto-load: true
  # Auto-check for new modules periodically
  auto-check: true
  # Check interval in seconds
  check-interval: 30
  # Load mode: STARTUP_ONLY, ON_DEMAND, PERIODICALLY
  load-mode: "STARTUP_ONLY"
  # Watch for module file changes (hot reload)
  hot-reload: true
  # Watcher check interval in seconds
  watcher-interval: 5
  # Timeout for module loading in milliseconds
  module-load-timeout: 30000
  # Ignore failed dependencies
  ignore-failed-dependencies: true
  # Extract module resources
  extract-resources: true
  # Force specific modules to load synchronously (list)
  force-sync-modules: []

#---------------------------------
# Console Output
#---------------------------------
console:
  # Enable colored console output
  colors: true
  # Show timestamps in console output
  timestamps: false
  # Use Unicode symbols for message types
  unicode-symbols: true
  # Style preset: default, minimal, or fancy
  style: "default"
  # Show startup animation
  startup-animation: true
  # Verbosity level: verbose, normal, minimal
  verbosity: "normal"
  
  # Component prefixes
  prefixes:
    core: "&8[&b&lApiCore&8]"
    module-manager: "&8[&d&lModuleManager&8]"
    file-manager: "&8[&6&lFileManager&8]"
    thread-manager: "&8[&a&lThreadManager&8]"
    resource-manager: "&8[&3&lResourceManager&8]"
    permission-manager: "&8[&5&lPermissionManager&8]"
    command-manager: "&8[&e&lCommandManager&8]"
    config-manager: "&8[&9&lConfigManager&8]"
    performance-monitor: "&8[&2&lPerformance&8]"
  
  # Message categories
  categories:
    enable-all: true
    system:    { enabled: true, prefix: "SYS",    color: "BRIGHT_CYAN",   icon: "⚡" }
    config:    { enabled: true, prefix: "CFG",    color: "BRIGHT_BLUE",   icon: "⚙" }
    module:    { enabled: true, prefix: "MOD",    color: "BRIGHT_GREEN",  icon: "📦" }
    performance:{ enabled: true, prefix: "PERF",  color: "BRIGHT_YELLOW", icon: "📊" }
    security:  { enabled: true, prefix: "SEC",    color: "BRIGHT_RED",    icon: "🔒" }
    network:   { enabled: true, prefix: "NET",    color: "BRIGHT_PURPLE", icon: "🌐" }
    database:  { enabled: true, prefix: "DB",     color: "BRIGHT_WHITE",  icon: "💾" }
    user:      { enabled: true, prefix: "USER",   color: "BLUE",          icon: "👤" }
    thread:    { enabled: true, prefix: "THREAD", color: "YELLOW",        icon: "🧵" }
    resource:  { enabled: true, prefix: "RES",    color: "GREEN",         icon: "📄" }

#---------------------------------
# Performance Optimizations
#---------------------------------
performance:
  # Enable performance monitoring
  enable-monitoring: true
  
  # Thread pool configuration
  threads:
    # Thread pool size (Default: processor count)
    pool-size: 4
    # Thread pool type: CACHED, FIXED, WORK_STEALING, SCHEDULED, ADVANCED
    pool-type: "CACHED"
    # Create high priority threads
    high-priority: false
    # Optimize for multiple cores
    optimize-cores: true
    # Optimize thread memory on startup
    optimize-memory: true
    # Enable thread monitoring
    monitoring: true
  
  # Memory optimizations
  memory:
    # Optimization level: low, medium, high
    level: "medium"
    # Maximum module memory in MB
    max-module-memory: 256
    # Minimize hard references
    minimize-references: true
    # GC threshold percentage
    gc-threshold: 80
    # Maximum cache size in MB
    max-cache-size: 128
    # Compress large data structures
    compress-large-data: false
    # Auto-flush inactive cache
    auto-flush: true
    # Flush after minutes of inactivity
    flush-after-minutes: 30
  
  # Cache settings
  cache:
    # Method cache size
    methods: 500
    # Reflection cache size
    reflection: 200
    # Use method handles (better performance)
    use-method-handles: true
    # Off-heap cache size in MB (0 = disabled)
    off-heap-size: 64
  
  # I/O operations
  io:
    # Buffer size for I/O operations
    buffer-size: 8192
  
  # Advanced thread pool settings
  advanced-pool:
    # Enable advanced thread pool
    enabled: true
    # Monitor thread pool
    monitoring: true
    # Minimum thread count
    min-threads: 2
    # Maximum thread count
    max-threads: 8
    # Thread idle timeout in seconds
    idle-timeout: 60
    # Pre-warm thread pool
    warm-up: true
    # Enable task prioritization
    prioritization: true
    # Queue size
    queue-size: 1000
  
  # Module performance tracking
  module-tracking:
    # Enable module performance tracking
    enabled: true
    # CPU warning threshold percentage
    cpu-warning-threshold: 20
    # CPU critical threshold percentage
    cpu-critical-threshold: 40
    # Memory warning threshold MB
    memory-warning-threshold: 25
    # Memory critical threshold MB
    memory-critical-threshold: 50
    # Execution time warning threshold ms
    execution-warning-threshold: 100
    # Execution time critical threshold ms
    execution-critical-threshold: 250
  
  # Deadlock detection and resolution
  deadlock:
    # Enable deadlock detection
    enabled: true
    # Check interval in seconds
    check-interval: 60
    # Enable automatic recovery attempts
    auto-recovery: true
    # Maximum recovery attempts
    max-recovery-attempts: 3
    # Log detailed deadlock information
    detailed-logging: true
  
  # Performance monitoring
  monitoring:
    # Data collection interval in seconds
    interval: 60
    # Log interval in minutes
    log-interval: 10
    # Maximum log files
    max-log-files: 10
    # Features to monitor
    features:
      cpu: true
      memory: true
      threads: true
      database: false
      network: false
    # Warning thresholds
    thresholds:
      cpu: 80
      memory: 85
    # Log to file
    log-to-file: true
    # Enable log rotation
    log-rotation: true

#---------------------------------
# Security Settings
#---------------------------------
security:
  # Enable sandbox for module execution
  enable-sandbox: true
  # Sandbox security level: low, medium, high
  sandbox-level: "medium"
  # Trusted modules that bypass sandbox
  trusted-modules: []
  # Block dangerous reflection
  block-dangerous-reflection: true
  # Limited file system access
  limited-filesystem-access: true
  # Block system commands
  block-system-commands: true
  # Maximum allowed threads per module
  max-threads-per-module: 5

#---------------------------------
# Command System
#---------------------------------
commands:
  # Reload commands after changes
  auto-reload: true
  # Default permission node prefix
  permission-prefix: "apicore"
  # Respect Bukkit permissions
  respect-bukkit-permissions: true
  # Default command tab completions
  default-completions: true
  # Log command executions
  log-executions: false
  # Maximum arguments per command
  max-args: 64
  # Disabled API Core commands
  disabled: []
