name: EssentialsCore
version: 1.0.12
main: com.essentialscore.ApiCore
api-version: 1.16
description: EssentialsCore - Advanced Minecraft Server Management with Module System & Integrations
author: Baumkrieger69
website: https://github.com/Baumkrieger69/EssentialsCore
load: STARTUP

# Default language setting
language: en_US

commands:
  apicore:
    description: Main command for controlling the EssentialsCore system
    usage: |
      /apicore help - Show all available commands
      /apicore modules [list|info|load|unload|reload|enable|disable] - Manage modules
      /apicore language [set|list|reload] - Manage languages  
      /apicore performance [status|report|benchmark|bossbar] - View performance data
      /apicore backup [create|list|restore|delete|settings] - Manage backups
      /apicore permissions [info|set|groups|check] - Manage permissions
      /apicore security [status|whitelist|blacklist|monitor] - Security management
      /apicore reload - Reload plugin configuration
      /apicore debug [on|off|status] - Toggle debug mode
    aliases: [acore, ac, ess, essentials, core, ec, esscore]
    permission: apicore.admin
  confirm:
    description: Confirm dangerous clickable commands
    usage: /confirm <confirmation-code>
    permission: apicore.use
permissions:
  # Core permissions
  apicore.admin:
    description: Grants access to all EssentialsCore commands
    default: op
  apicore.use:
    description: Allows basic usage of EssentialsCore features
    default: true
  apicore.admin.*:
    description: Grants all administrative permissions
    default: op
    children:
      apicore.admin: true
      apicore.admin.modules: true
      apicore.admin.system: true
      apicore.admin.performance: true
      apicore.admin.security: true
      apicore.admin.backup: true
      apicore.admin.permissions: true
      apicore.admin.integrations: true
  
  # Module management
  apicore.admin.modules:
    description: Grants access to module management commands
    default: op
    children:
      apicore.admin.modules.list: true
      apicore.admin.modules.load: true
      apicore.admin.modules.unload: true
      apicore.admin.modules.reload: true
      apicore.admin.modules.enable: true
      apicore.admin.modules.disable: true
      apicore.admin.modules.info: true
  apicore.admin.modules.list:
    description: Allows listing modules
    default: op
  apicore.admin.modules.load:
    description: Allows loading modules
    default: op
  apicore.admin.modules.unload:
    description: Allows unloading modules
    default: op
  apicore.admin.modules.reload:
    description: Allows reloading modules
    default: op
  apicore.admin.modules.enable:
    description: Allows enabling modules
    default: op
  apicore.admin.modules.disable:
    description: Allows disabling modules
    default: op
  apicore.admin.modules.info:
    description: Allows viewing module information
    default: op
  
  # System administration
  apicore.admin.system:
    description: Allows access to system-level features
    default: op
    children:
      apicore.admin.system.reload: true
      apicore.admin.system.debug: true
      apicore.admin.system.cache: true
      apicore.admin.system.threads: true
      apicore.admin.system.memory: true
  apicore.admin.system.reload:
    description: Allows reloading the plugin configuration
    default: op
  apicore.admin.system.debug:
    description: Allows toggling debug mode
    default: op
  apicore.admin.system.cache:
    description: Allows managing system caches
    default: op
  apicore.admin.system.threads:
    description: Allows managing thread pools
    default: op
  apicore.admin.system.memory:
    description: Allows memory management operations
    default: op
  
  # Performance monitoring
  apicore.admin.performance:
    description: Grants access to performance monitoring
    default: op
    children:
      apicore.admin.performance.view: true
      apicore.admin.performance.benchmark: true
      apicore.admin.performance.bossbar: true
      apicore.admin.performance.reports: true
  apicore.admin.performance.view:
    description: Allows viewing performance data
    default: op
  apicore.admin.performance.benchmark:
    description: Allows running benchmarks
    default: op
  apicore.admin.performance.bossbar:
    description: Allows toggling performance bossbar
    default: op
  apicore.admin.performance.reports:
    description: Allows generating performance reports
    default: op
  
  # Security management
  apicore.admin.security:
    description: Grants access to security features
    default: op
    children:
      apicore.admin.security.view: true
      apicore.admin.security.whitelist: true
      apicore.admin.security.blacklist: true
      apicore.admin.security.monitor: true
  apicore.admin.security.view:
    description: Allows viewing security status
    default: op
  apicore.admin.security.whitelist:
    description: Allows managing security whitelist
    default: op
  apicore.admin.security.blacklist:
    description: Allows managing security blacklist
    default: op
  apicore.admin.security.monitor:
    description: Allows toggling security monitoring
    default: op
  
  # Backup management
  apicore.admin.backup:
    description: Grants access to backup management
    default: op
    children:
      apicore.admin.backup.create: true
      apicore.admin.backup.list: true
      apicore.admin.backup.restore: true
      apicore.admin.backup.delete: true
      apicore.admin.backup.settings: true
  apicore.admin.backup.create:
    description: Allows creating backups
    default: op
  apicore.admin.backup.list:
    description: Allows listing backups
    default: op
  apicore.admin.backup.restore:
    description: Allows restoring backups
    default: op
  apicore.admin.backup.delete:
    description: Allows deleting backups
    default: op
  apicore.admin.backup.settings:
    description: Allows viewing backup settings
    default: op
  
  # Permission management
  apicore.admin.permissions:
    description: Grants access to permission management
    default: op
    children:
      apicore.admin.permissions.view: true
      apicore.admin.permissions.set: true
      apicore.admin.permissions.groups: true
      apicore.admin.permissions.check: true
  apicore.admin.permissions.view:
    description: Allows viewing permission information
    default: op
  apicore.admin.permissions.set:
    description: Allows setting player permissions
    default: op
  apicore.admin.permissions.groups:
    description: Allows managing permission groups
    default: op
  apicore.admin.permissions.check:
    description: Allows checking player permissions
    default: op
  
  # Integration management
  apicore.admin.integrations:
    description: Grants access to integration management
    default: op
    children:
      apicore.admin.integrations.vault: true
      apicore.admin.integrations.placeholderapi: true
      apicore.admin.integrations.luckperms: true
  apicore.admin.integrations.vault:
    description: Allows managing Vault integration
    default: op
  apicore.admin.integrations.placeholderapi:
    description: Allows managing PlaceholderAPI integration
    default: op
  apicore.admin.integrations.luckperms:
    description: Allows managing LuckPerms integration
    default: op

# Soft dependencies for integrations
softdepend: [Vault, PlaceholderAPI, WorldEdit, WorldGuard, LuckPerms, Citizens, MythicMobs, ProtocolLib]

# Plugin load order
loadbefore: [Essentials, EssentialsX]